name: inventario_app
description: "AplicaciÃ³n de inventario para Retablo's CafÃ©"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1   # ðŸ‘ˆ aÃ±adido para personalizar icono

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"   # ðŸ‘ˆ tu logo aquÃ­
  adaptive_icon_background: "#6B4226"      # marrÃ³n cafÃ©
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png   # ðŸ‘ˆ asegÃºrate de tener tu logo en esta ruta